apiVersion: apps/v1
kind: Deployment
metadata:
  name: azureexample-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: azureexample-app
  template:
    metadata:
      labels:
        app: azureexample-app
    spec:
      containers:
      - name: azureexample-app
        image: myacrrepo1234.azurecr.io/nikit12345/azuredeployeeexample
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: azureexample-app
    k8s-app: azureexample-app
  name: azureexample-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8082
  type: LoadBalancer
  selector:
    app: azureexample-app
