apiVersion: apps/v1
kind: Deployment
metadata:
  name: AzureDeployeeExample-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: azureDeployeeExample-app
  template:
    metadata:
      labels:
        app: azureDeployeeExample-app
    spec:
      containers:
      - name: azureDeployeeExample-app
        image: myacrrepo1234.azurecr.io/nikit12345/AzureDeployeeExample:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: azureDeployeeExample-app
    k8s-app: azureDeployeeExample-app
  name: azureDeployeeExample-app
spec:
  ports:
  - name: http
    port: 90
    protocol: TCP
    targetPort: 9090
  type: LoadBalancer
  selector:
    app: azureDeployeeExample-app